<!DOCTYPE html>
<html><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8"><meta name="viewport" content="width=device-width"><title>https://
www.ryanchuangmd.com/wp-login.php?
redirect_to=https%3A%2F%2Fwww.ryanchuangmd.com%2Fwp-admin%2Fauthorize-
application.php&amp;reauth=1</title><link rel="stylesheet" type="text/css" href="resource://content-accessible/viewsource.css"></head><body id="viewsource" style="tab-size: 4"><pre id="line1"><span></span><span class="doctype">&lt;!DOCTYPE html&gt;</span><span>
<span id="line2"></span>	</span><span>&lt;<span class="start-tag">html</span> <span class="attribute-name">lang</span>="<a class="attribute-value">en-US</a>"&gt;</span><span>
<span id="line3"></span>	</span><span>&lt;<span class="start-tag">head</span>&gt;</span><span>
<span id="line4"></span>	</span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">http-equiv</span>="<a class="attribute-value">Content-Type</a>" <span class="attribute-name">content</span>="<a class="attribute-value">text/html; charset=UTF-8</a>" <span>/</span>&gt;</span><span>
<span id="line5"></span>	</span><span>&lt;<span class="start-tag">title</span>&gt;</span><span>Log In <span class="entity"><span>&amp;</span>lsaquo;</span> Ryan J. Chuang, MD, MPhil <span class="entity"><span>&amp;</span>#8212;</span> WordPress</span><span>&lt;/<span class="end-tag">title</span>&gt;</span><span>
<span id="line6"></span>	</span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">name</span>='<a class="attribute-value">robots</a>' <span class="attribute-name">content</span>='<a class="attribute-value">noindex, follow</a>' <span>/</span>&gt;</span><span>
<span id="line7"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">type</span>="<a class="attribute-value">text/javascript</a>" <span class="attribute-name">src</span>="<a class="attribute-value" href="view-source:https://www.ryanchuangmd.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1">https://www.ryanchuangmd.com/wp-includes/js/jquery/jquery.min.js?ver=3.7.1</a>" <span class="attribute-name">id</span>="<a class="attribute-value">jquery-core-js</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line8"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">type</span>="<a class="attribute-value">text/javascript</a>" <span class="attribute-name">src</span>="<a class="attribute-value" href="view-source:https://www.ryanchuangmd.com/wp-includes/js/jquery/jquery-migrate.min.js?ver=3.4.1">https://www.ryanchuangmd.com/wp-includes/js/jquery/jquery-migrate.min.js?ver=3.4.1</a>" <span class="attribute-name">id</span>="<a class="attribute-value">jquery-migrate-js</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line9"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">type</span>="<a class="attribute-value">text/javascript</a>" <span class="attribute-name">src</span>="<a class="attribute-value" href="view-source:https://www.ryanchuangmd.com/wp-content/mu-plugins/force-strong-passwords/force-zxcvbn.min.js?ver=1.8.0">https://www.ryanchuangmd.com/wp-content/mu-plugins/force-strong-passwords/force-zxcvbn.min.js?ver=1.8.0</a>" <span class="attribute-name">id</span>="<a class="attribute-value">slt-fsp-force-zxcvbn-js</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line10"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">type</span>="<a class="attribute-value">text/javascript</a>" <span class="attribute-name">src</span>="<a class="attribute-value" href="view-source:https://www.ryanchuangmd.com/wp-content/mu-plugins/force-strong-passwords/js-admin.min.js?ver=1.8.0">https://www.ryanchuangmd.com/wp-content/mu-plugins/force-strong-passwords/js-admin.min.js?ver=1.8.0</a>" <span class="attribute-name">id</span>="<a class="attribute-value">slt-fsp-admin-js-js</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line11"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>='<a class="attribute-value">stylesheet</a>' <span class="attribute-name">id</span>='<a class="attribute-value">dashicons-css</a>' <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:https://www.ryanchuangmd.com/wp-includes/css/dashicons.min.css?ver=6.6.1">https://www.ryanchuangmd.com/wp-includes/css/dashicons.min.css?ver=6.6.1</a>' <span class="attribute-name">type</span>='<a class="attribute-value">text/css</a>' <span class="attribute-name">media</span>='<a class="attribute-value">all</a>' <span>/</span>&gt;</span><span>
<span id="line12"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>='<a class="attribute-value">stylesheet</a>' <span class="attribute-name">id</span>='<a class="attribute-value">buttons-css</a>' <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:https://www.ryanchuangmd.com/wp-includes/css/buttons.min.css?ver=6.6.1">https://www.ryanchuangmd.com/wp-includes/css/buttons.min.css?ver=6.6.1</a>' <span class="attribute-name">type</span>='<a class="attribute-value">text/css</a>' <span class="attribute-name">media</span>='<a class="attribute-value">all</a>' <span>/</span>&gt;</span><span>
<span id="line13"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>='<a class="attribute-value">stylesheet</a>' <span class="attribute-name">id</span>='<a class="attribute-value">forms-css</a>' <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:https://www.ryanchuangmd.com/wp-admin/css/forms.min.css?ver=6.6.1">https://www.ryanchuangmd.com/wp-admin/css/forms.min.css?ver=6.6.1</a>' <span class="attribute-name">type</span>='<a class="attribute-value">text/css</a>' <span class="attribute-name">media</span>='<a class="attribute-value">all</a>' <span>/</span>&gt;</span><span>
<span id="line14"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>='<a class="attribute-value">stylesheet</a>' <span class="attribute-name">id</span>='<a class="attribute-value">l10n-css</a>' <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:https://www.ryanchuangmd.com/wp-admin/css/l10n.min.css?ver=6.6.1">https://www.ryanchuangmd.com/wp-admin/css/l10n.min.css?ver=6.6.1</a>' <span class="attribute-name">type</span>='<a class="attribute-value">text/css</a>' <span class="attribute-name">media</span>='<a class="attribute-value">all</a>' <span>/</span>&gt;</span><span>
<span id="line15"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>='<a class="attribute-value">stylesheet</a>' <span class="attribute-name">id</span>='<a class="attribute-value">login-css</a>' <span class="attribute-name">href</span>='<a class="attribute-value" href="view-source:https://www.ryanchuangmd.com/wp-admin/css/login.min.css?ver=6.6.1">https://www.ryanchuangmd.com/wp-admin/css/login.min.css?ver=6.6.1</a>' <span class="attribute-name">type</span>='<a class="attribute-value">text/css</a>' <span class="attribute-name">media</span>='<a class="attribute-value">all</a>' <span>/</span>&gt;</span><span>
<span id="line16"></span>	</span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">name</span>='<a class="attribute-value">referrer</a>' <span class="attribute-name">content</span>='<a class="attribute-value">strict-origin-when-cross-origin</a>' <span>/</span>&gt;</span><span>
<span id="line17"></span>		</span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">name</span>="<a class="attribute-value">viewport</a>" <span class="attribute-name">content</span>="<a class="attribute-value">width=device-width</a>" <span>/</span>&gt;</span><span>
<span id="line18"></span>	</span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">icon</a>" <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:https://www.ryanchuangmd.com/wp-content/uploads/2021/10/cropped-ryanchuangmd-symbol@2x-32x32.jpg">https://www.ryanchuangmd.com/wp-content/uploads/2021/10/cropped-ryanchuangmd-symbol@2x-32x32.jpg</a>" <span class="attribute-name">sizes</span>="<a class="attribute-value">32x32</a>" <span>/</span>&gt;</span><span>
<span id="line19"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">icon</a>" <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:https://www.ryanchuangmd.com/wp-content/uploads/2021/10/cropped-ryanchuangmd-symbol@2x-192x192.jpg">https://www.ryanchuangmd.com/wp-content/uploads/2021/10/cropped-ryanchuangmd-symbol@2x-192x192.jpg</a>" <span class="attribute-name">sizes</span>="<a class="attribute-value">192x192</a>" <span>/</span>&gt;</span><span>
<span id="line20"></span></span><span>&lt;<span class="start-tag">link</span> <span class="attribute-name">rel</span>="<a class="attribute-value">apple-touch-icon</a>" <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:https://www.ryanchuangmd.com/wp-content/uploads/2021/10/cropped-ryanchuangmd-symbol@2x-180x180.jpg">https://www.ryanchuangmd.com/wp-content/uploads/2021/10/cropped-ryanchuangmd-symbol@2x-180x180.jpg</a>" <span>/</span>&gt;</span><span>
<span id="line21"></span></span><span>&lt;<span class="start-tag">meta</span> <span class="attribute-name">name</span>="<a class="attribute-value">msapplication-TileImage</a>" <span class="attribute-name">content</span>="<a class="attribute-value">https://www.ryanchuangmd.com/wp-content/uploads/2021/10/cropped-ryanchuangmd-symbol@2x-270x270.jpg</a>" <span>/</span>&gt;</span><span>
<span id="line22"></span>	</span><span>&lt;/<span class="end-tag">head</span>&gt;</span><span>
<span id="line23"></span>	</span><span>&lt;<span class="start-tag">body</span> <span class="attribute-name">class</span>="<a class="attribute-value">login no-js login-action-login wp-core-ui  locale-en-us</a>"&gt;</span><span>
<span id="line24"></span>	</span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">type</span>="<a class="attribute-value">text/javascript</a>"&gt;</span><span>
<span id="line25"></span>/* </span><span>&lt;!</span><span>[CDATA[ */
<span id="line26"></span>document.body.className = document.body.className.replace('no-js','js');
<span id="line27"></span>/* ]]&gt; */
<span id="line28"></span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line29"></span>
<span id="line30"></span>		</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">id</span>="<a class="attribute-value">login</a>"&gt;</span><span>
<span id="line31"></span>		</span><span>&lt;<span class="start-tag">h1</span>&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:https://wordpress.org/">https://wordpress.org/</a>"&gt;</span><span>Powered by WordPress</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">h1</span>&gt;</span><span>
<span id="line32"></span>	</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">id</span>="<a class="attribute-value">login-message</a>" <span class="attribute-name">class</span>="<a class="attribute-value">notice notice-info message</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">p</span>&gt;</span><span>Please log in to Ryan J. Chuang, MD, MPhil to proceed with authorization.</span><span>&lt;/<span class="end-tag">p</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line33"></span>		</span><span>&lt;<span class="start-tag">form</span> <span class="attribute-name">name</span>="<a class="attribute-value">loginform</a>" <span class="attribute-name">id</span>="<a class="attribute-value">loginform</a>" <span class="attribute-name">action</span>="<a class="attribute-value" href="view-source:https://www.ryanchuangmd.com/wp-login.php?wpe-login=true">https://www.ryanchuangmd.com/wp-login.php?wpe-login=true</a>" <span class="attribute-name">method</span>="<a class="attribute-value">post</a>"&gt;</span><span>
<span id="line34"></span>			</span><span>&lt;<span class="start-tag">p</span>&gt;</span><span>
<span id="line35"></span>				</span><span>&lt;<span class="start-tag">label</span> <span class="attribute-name">for</span>="<a class="attribute-value">user_login</a>"&gt;</span><span>Username or Email Address</span><span>&lt;/<span class="end-tag">label</span>&gt;</span><span>
<span id="line36"></span>				</span><span>&lt;<span class="start-tag">input</span> <span class="attribute-name">type</span>="<a class="attribute-value">text</a>" <span class="attribute-name">name</span>="<a class="attribute-value">log</a>" <span class="attribute-name">id</span>="<a class="attribute-value">user_login</a>" <span class="attribute-name">aria-describedby</span>="<a class="attribute-value">login-message</a>" <span class="attribute-name">class</span>="<a class="attribute-value">input</a>" <span class="attribute-name">value</span>="<a class="attribute-value"></a>" <span class="attribute-name">size</span>="<a class="attribute-value">20</a>" <span class="attribute-name">autocapitalize</span>="<a class="attribute-value">off</a>" <span class="attribute-name">autocomplete</span>="<a class="attribute-value">username</a>" <span class="attribute-name">required</span>="<a class="attribute-value">required</a>" <span>/</span>&gt;</span><span>
<span id="line37"></span>			</span><span>&lt;/<span class="end-tag">p</span>&gt;</span><span>
<span id="line38"></span>
<span id="line39"></span>			</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">user-pass-wrap</a>"&gt;</span><span>
<span id="line40"></span>				</span><span>&lt;<span class="start-tag">label</span> <span class="attribute-name">for</span>="<a class="attribute-value">user_pass</a>"&gt;</span><span>Password</span><span>&lt;/<span class="end-tag">label</span>&gt;</span><span>
<span id="line41"></span>				</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">wp-pwd</a>"&gt;</span><span>
<span id="line42"></span>					</span><span>&lt;<span class="start-tag">input</span> <span class="attribute-name">type</span>="<a class="attribute-value">password</a>" <span class="attribute-name">name</span>="<a class="attribute-value">pwd</a>" <span class="attribute-name">id</span>="<a class="attribute-value">user_pass</a>" <span class="attribute-name">aria-describedby</span>="<a class="attribute-value">login-message</a>" <span class="attribute-name">class</span>="<a class="attribute-value">input password-input</a>" <span class="attribute-name">value</span>="<a class="attribute-value"></a>" <span class="attribute-name">size</span>="<a class="attribute-value">20</a>" <span class="attribute-name">autocomplete</span>="<a class="attribute-value">current-password</a>" <span class="attribute-name">spellcheck</span>="<a class="attribute-value">false</a>" <span class="attribute-name">required</span>="<a class="attribute-value">required</a>" <span>/</span>&gt;</span><span>
<span id="line43"></span>					</span><span>&lt;<span class="start-tag">button</span> <span class="attribute-name">type</span>="<a class="attribute-value">button</a>" <span class="attribute-name">class</span>="<a class="attribute-value">button button-secondary wp-hide-pw hide-if-no-js</a>" <span class="attribute-name">data-toggle</span>="<a class="attribute-value">0</a>" <span class="attribute-name">aria-label</span>="<a class="attribute-value">Show password</a>"&gt;</span><span>
<span id="line44"></span>						</span><span>&lt;<span class="start-tag">span</span> <span class="attribute-name">class</span>="<a class="attribute-value">dashicons dashicons-visibility</a>" <span class="attribute-name">aria-hidden</span>="<a class="attribute-value">true</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">span</span>&gt;</span><span>
<span id="line45"></span>					</span><span>&lt;/<span class="end-tag">button</span>&gt;</span><span>
<span id="line46"></span>				</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line47"></span>			</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line48"></span>						</span><span>&lt;<span class="start-tag">p</span> <span class="attribute-name">class</span>="<a class="attribute-value">forgetmenot</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">input</span> <span class="attribute-name">name</span>="<a class="attribute-value">rememberme</a>" <span class="attribute-name">type</span>="<a class="attribute-value">checkbox</a>" <span class="attribute-name">id</span>="<a class="attribute-value">rememberme</a>" <span class="attribute-name">value</span>="<a class="attribute-value">forever</a>"  <span>/</span>&gt;</span><span> </span><span>&lt;<span class="start-tag">label</span> <span class="attribute-name">for</span>="<a class="attribute-value">rememberme</a>"&gt;</span><span>Remember Me</span><span>&lt;/<span class="end-tag">label</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">p</span>&gt;</span><span>
<span id="line49"></span>			</span><span>&lt;<span class="start-tag">p</span> <span class="attribute-name">class</span>="<a class="attribute-value">submit</a>"&gt;</span><span>
<span id="line50"></span>				</span><span>&lt;<span class="start-tag">input</span> <span class="attribute-name">type</span>="<a class="attribute-value">submit</a>" <span class="attribute-name">name</span>="<a class="attribute-value">wp-submit</a>" <span class="attribute-name">id</span>="<a class="attribute-value">wp-submit</a>" <span class="attribute-name">class</span>="<a class="attribute-value">button button-primary button-large</a>" <span class="attribute-name">value</span>="<a class="attribute-value">Log In</a>" <span>/</span>&gt;</span><span>
<span id="line51"></span>									</span><span>&lt;<span class="start-tag">input</span> <span class="attribute-name">type</span>="<a class="attribute-value">hidden</a>" <span class="attribute-name">name</span>="<a class="attribute-value">redirect_to</a>" <span class="attribute-name">value</span>="<a class="attribute-value">https://www.ryanchuangmd.com/wp-admin/authorize-application.php</a>" <span>/</span>&gt;</span><span>
<span id="line52"></span>									</span><span>&lt;<span class="start-tag">input</span> <span class="attribute-name">type</span>="<a class="attribute-value">hidden</a>" <span class="attribute-name">name</span>="<a class="attribute-value">testcookie</a>" <span class="attribute-name">value</span>="<a class="attribute-value">1</a>" <span>/</span>&gt;</span><span>
<span id="line53"></span>			</span><span>&lt;/<span class="end-tag">p</span>&gt;</span><span>
<span id="line54"></span>		</span><span>&lt;/<span class="end-tag">form</span>&gt;</span><span>
<span id="line55"></span>
<span id="line56"></span>					</span><span>&lt;<span class="start-tag">p</span> <span class="attribute-name">id</span>="<a class="attribute-value">nav</a>"&gt;</span><span>
<span id="line57"></span>				</span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>="<a class="attribute-value">wp-login-lost-password</a>" <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:https://www.ryanchuangmd.com/wp-login.php?action=lostpassword">https://www.ryanchuangmd.com/wp-login.php?action=lostpassword</a>"&gt;</span><span>Lost your password?</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span>			</span><span>&lt;/<span class="end-tag">p</span>&gt;</span><span>
<span id="line58"></span>			</span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">type</span>="<a class="attribute-value">text/javascript</a>"&gt;</span><span>
<span id="line59"></span>/* </span><span>&lt;!</span><span>[CDATA[ */
<span id="line60"></span>function wp_attempt_focus() {setTimeout( function() {try {d = document.getElementById( "user_login" );d.focus(); d.select();} catch( er ) {}}, 200);}
<span id="line61"></span>wp_attempt_focus();
<span id="line62"></span>if ( typeof wpOnload === 'function' ) { wpOnload() }
<span id="line63"></span>/* ]]&gt; */
<span id="line64"></span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line65"></span>		</span><span>&lt;<span class="start-tag">p</span> <span class="attribute-name">id</span>="<a class="attribute-value">backtoblog</a>"&gt;</span><span>
<span id="line66"></span>			</span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:https://www.ryanchuangmd.com/">https://www.ryanchuangmd.com/</a>"&gt;</span><span><span class="entity"><span>&amp;</span>larr;</span> Go to Ryan J. Chuang, MD, MPhil</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span>		</span><span>&lt;/<span class="end-tag">p</span>&gt;</span><span>
<span id="line67"></span>		</span><span>&lt;<span class="start-tag">div</span> <span class="attribute-name">class</span>="<a class="attribute-value">privacy-policy-page-link</a>"&gt;</span><span></span><span>&lt;<span class="start-tag">a</span> <span class="attribute-name">class</span>="<a class="attribute-value">privacy-policy-link</a>" <span class="attribute-name">href</span>="<a class="attribute-value" href="view-source:https://www.ryanchuangmd.com/privacy-policy/">https://www.ryanchuangmd.com/privacy-policy/</a>" <span class="attribute-name">rel</span>="<a class="attribute-value">privacy-policy</a>"&gt;</span><span>Privacy Policy</span><span>&lt;/<span class="end-tag">a</span>&gt;</span><span></span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>	</span><span>&lt;/<span class="end-tag">div</span>&gt;</span><span>
<span id="line68"></span>			</span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">type</span>="<a class="attribute-value">text/javascript</a>" <span class="attribute-name">id</span>="<a class="attribute-value">zxcvbn-async-js-extra</a>"&gt;</span><span>
<span id="line69"></span>/* </span><span>&lt;!</span><span>[CDATA[ */
<span id="line70"></span>var _zxcvbnSettings = {"src":"https:\/\/www.ryanchuangmd.com\/wp-includes\/js\/zxcvbn.min.js"};
<span id="line71"></span>/* ]]&gt; */
<span id="line72"></span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line73"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">type</span>="<a class="attribute-value">text/javascript</a>" <span class="attribute-name">src</span>="<a class="attribute-value" href="view-source:https://www.ryanchuangmd.com/wp-includes/js/zxcvbn-async.min.js?ver=1.0">https://www.ryanchuangmd.com/wp-includes/js/zxcvbn-async.min.js?ver=1.0</a>" <span class="attribute-name">id</span>="<a class="attribute-value">zxcvbn-async-js</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line74"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">type</span>="<a class="attribute-value">text/javascript</a>" <span class="attribute-name">src</span>="<a class="attribute-value" href="view-source:https://www.ryanchuangmd.com/wp-includes/js/dist/hooks.min.js?ver=2810c76e705dd1a53b18">https://www.ryanchuangmd.com/wp-includes/js/dist/hooks.min.js?ver=2810c76e705dd1a53b18</a>" <span class="attribute-name">id</span>="<a class="attribute-value">wp-hooks-js</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line75"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">type</span>="<a class="attribute-value">text/javascript</a>" <span class="attribute-name">src</span>="<a class="attribute-value" href="view-source:https://www.ryanchuangmd.com/wp-includes/js/dist/i18n.min.js?ver=5e580eb46a90c2b997e6">https://www.ryanchuangmd.com/wp-includes/js/dist/i18n.min.js?ver=5e580eb46a90c2b997e6</a>" <span class="attribute-name">id</span>="<a class="attribute-value">wp-i18n-js</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line76"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">type</span>="<a class="attribute-value">text/javascript</a>" <span class="attribute-name">id</span>="<a class="attribute-value">wp-i18n-js-after</a>"&gt;</span><span>
<span id="line77"></span>/* </span><span>&lt;!</span><span>[CDATA[ */
<span id="line78"></span>wp.i18n.setLocaleData( { 'text direction\u0004ltr': [ 'ltr' ] } );
<span id="line79"></span>/* ]]&gt; */
<span id="line80"></span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line81"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">type</span>="<a class="attribute-value">text/javascript</a>" <span class="attribute-name">id</span>="<a class="attribute-value">password-strength-meter-js-extra</a>"&gt;</span><span>
<span id="line82"></span>/* </span><span>&lt;!</span><span>[CDATA[ */
<span id="line83"></span>var pwsL10n = {"unknown":"Password strength unknown","short":"Very weak","bad":"Weak","good":"Medium","strong":"Strong","mismatch":"Mismatch"};
<span id="line84"></span>/* ]]&gt; */
<span id="line85"></span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line86"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">type</span>="<a class="attribute-value">text/javascript</a>" <span class="attribute-name">src</span>="<a class="attribute-value" href="view-source:https://www.ryanchuangmd.com/wp-admin/js/password-strength-meter.min.js?ver=6.6.1">https://www.ryanchuangmd.com/wp-admin/js/password-strength-meter.min.js?ver=6.6.1</a>" <span class="attribute-name">id</span>="<a class="attribute-value">password-strength-meter-js</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line87"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">type</span>="<a class="attribute-value">text/javascript</a>" <span class="attribute-name">src</span>="<a class="attribute-value" href="view-source:https://www.ryanchuangmd.com/wp-includes/js/underscore.min.js?ver=1.13.4">https://www.ryanchuangmd.com/wp-includes/js/underscore.min.js?ver=1.13.4</a>" <span class="attribute-name">id</span>="<a class="attribute-value">underscore-js</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line88"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">type</span>="<a class="attribute-value">text/javascript</a>" <span class="attribute-name">id</span>="<a class="attribute-value">wp-util-js-extra</a>"&gt;</span><span>
<span id="line89"></span>/* </span><span>&lt;!</span><span>[CDATA[ */
<span id="line90"></span>var _wpUtilSettings = {"ajax":{"url":"\/wp-admin\/admin-ajax.php"}};
<span id="line91"></span>/* ]]&gt; */
<span id="line92"></span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line93"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">type</span>="<a class="attribute-value">text/javascript</a>" <span class="attribute-name">src</span>="<a class="attribute-value" href="view-source:https://www.ryanchuangmd.com/wp-includes/js/wp-util.min.js?ver=6.6.1">https://www.ryanchuangmd.com/wp-includes/js/wp-util.min.js?ver=6.6.1</a>" <span class="attribute-name">id</span>="<a class="attribute-value">wp-util-js</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line94"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">type</span>="<a class="attribute-value">text/javascript</a>" <span class="attribute-name">id</span>="<a class="attribute-value">user-profile-js-extra</a>"&gt;</span><span>
<span id="line95"></span>/* </span><span>&lt;!</span><span>[CDATA[ */
<span id="line96"></span>var userProfileL10n = {"user_id":"0","nonce":"7bde81dac0"};
<span id="line97"></span>/* ]]&gt; */
<span id="line98"></span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line99"></span></span><span>&lt;<span class="start-tag">script</span> <span class="attribute-name">type</span>="<a class="attribute-value">text/javascript</a>" <span class="attribute-name">src</span>="<a class="attribute-value" href="view-source:https://www.ryanchuangmd.com/wp-admin/js/user-profile.min.js?ver=6.6.1">https://www.ryanchuangmd.com/wp-admin/js/user-profile.min.js?ver=6.6.1</a>" <span class="attribute-name">id</span>="<a class="attribute-value">user-profile-js</a>"&gt;</span><span></span><span>&lt;/<span class="end-tag">script</span>&gt;</span><span>
<span id="line100"></span>	</span><span>&lt;/<span class="end-tag">body</span>&gt;</span><span>
<span id="line101"></span>	</span><span>&lt;/<span class="end-tag">html</span>&gt;</span><span>
<span id="line102"></span>	</span></pre></body></html>